spring.application.name=InterviewHub.com

spring.mongodb.uri=mongodb+srv://bilalahmed20051:bilalahmednexium@cluster0.oomrgvf.mongodb.net/?appName=Cluster0
spring.mongodb.database=interviewhub
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.boot.context.config=DEBUG
