spring.application.name=InterviewHub.com

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${DATABASE_NAME}
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.boot.context.config=DEBUG
